### ISSUE TITLE
Not detecting I've launched a rocket, /ngp-gui has no effect

### ISSUE THREAD

**Issue by adamcharnock** [Bilka2/NewGamePlus#1]
Hello, thank you for making this mod, I'm really looking forward to using it!

The problems I'm having are twofold:

1. When I enter `/ngp-gui` on the console I am told that I need to change my settings to use the command without sending a rocket. **I have already sent up two rockets containing satellites.**
2. Nonetheless, I enable the option in my mod settings. I then run the command. Upon doing this nothing happens (no error provided, no GUI displayed)

Any suggestions would be very welcome indeed!

Thank you again

EDIT: Factorio 0.16.22, mac. Mod version 2.1.0

**Comment by adamcharnock** [comment]
Turns out I was being stupid! I hadn't seen the new button that had appeared at the top left of the screen.

Sorry about that! Maybe this will save someone else scratching their head!

<img width="856" alt="screen shot 2018-02-10 at 18 10 31" src="https://user-images.githubusercontent.com/138215/36065105-e7109f2e-0e8d-11e8-972c-c082132d98c4.png">

**Comment by Bilka2** [comment]
Well, I'm glad you found it :) I could change the locale a bit to make that more clear though, I'll think about it.
