### ISSUE TITLE
NewGame+ triggers a crash when Logistic Train Network is present.

### ISSUE THREAD

**Issue by dewiniaid** [Bilka2/NewGamePlus#2]
I get the following error with LTN when using the New Game+ mod and starting a 'new' game:

```
Error while running event LogisticTrainNetwork::on_train_created (ID 66)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	__LogisticTrainNetwork__/control.lua:1752: in function 'setLamp'
	__LogisticTrainNetwork__/control.lua:434: in function 'TrainLeaves'
	__LogisticTrainNetwork__/control.lua:515: in function <__LogisticTrainNetwork__/control.lua:509>
```

I've also an issue on [LTN's Github](https://github.com/Yousei9/Logistic-Train-Network/issues/139).

The issues here seem to be numerous:

* LTN expects to be notified when its entities are destroyed.
* NGP doesn't actually destroy entities, it instead destroys surfaces (or chunks when that surface is Nauvis)
* LTN doesn't watch for `on_[pre_]_surface_deleted`
* There's no Factorio event for `on_chunk_destroyed`

Yousei claims the issue is in your mod.  I feel that it's an issue that'd require some cooperation between both of you to find a good fix for -- maybe as simple as a remote interface that tells LTN to forget everything it knows.  Posting here for hope of collaboration.

**Comment by Bilka2** [comment]
This is in no way something that is on me to fix, but regardless of that I have reached out to the author of LTN. Thank you for notifying me of the problem, I hope we can come to a solution with the other mod author.

Closing this because it's not my bug.
